/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Kanit } from 'next/font/google'

const kanit = Kanit({
  weight:'400',
  subsets:['latin','thai']
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${kanit.className} antialiased`}
        >
          <Provider>
            <Navbar />
            <main className="container">{children}</main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
